[package]
name = "scrolls"
description = "Replay scribbles, drawings, doodles, convos..."
version.workspace = true
authors.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-stream.workspace = true
atomic.workspace = true
env_logger.workspace = true
function_name.workspace = true
futures.workspace = true
itertools.workspace = true
libremarkable.workspace = true
log.workspace = true
marauder.path = "../marauder"
nom.workspace = true
once_cell.workspace = true
pb.path = "../pb"
prost.workspace = true
quick-xml.workspace = true
rand.workspace = true
ringbuffer.workspace = true
serde-jsonlines.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio-stream.workspace = true
tokio.workspace = true
tonic.workspace = true
tower.workspace = true
