version: '3.8'
services:

  nats:
    image: docker.io/library/nats:2-alpine@sha256:8b3fb2423a8cce4607ef30a990b35545afe0a3c613cd05b8eec7b483df268b1d
    environment:
      # Only here so refs can be bound
      _1: &NATS_USER 'reMarkable-HyperCards'
      _2: &NATS_PASS 'iQ9KE4XNiq9XmCmGbbyjsQ7KP9DMHXL6yLGeFHfj'
    command:
    - --user
    - *NATS_USER
    - --pass
    - *NATS_PASS
    - -m
    - '8222'
    - -DVV
    # ports:
    # - '127.0.0.1:4222:4222'
    # - '127.0.0.1:6222:6222'
    # - '127.0.0.1:8222:8222'

  redis:
    image: docker.io/library/redis:5-alpine@sha256:a04b57e05b784a406bc818f6b450233328c4115a1e1f104d84ce916eb1583925
    environment:
      # Only here so refs can be bound
      _1: &REDIS_HOST 'redis'
      _2: &REDIS_PORT '6379'
      _3: &REDIS_PASSWORD '' # default
      _4: &REDIS_DB '0' # default
    volumes:
    - ./redis/redis.conf:/etc/redis/redis.conf:ro
    command: redis-server /etc/redis/redis.conf
    # ports:
    # - '127.0.0.1:6379:6379'

  http-server:
    depends_on:
    - redis
    build:
      context: ./whiteboard-server/
      target: http-server
    image: http-server
    hostname: http-server
    container_name: http-server
    restart: unless-stopped
    environment:
      PORT: '18888'
      PATH_PREFIX: /s
      REDIS_HOST: *REDIS_HOST
      REDIS_PORT: *REDIS_PORT
      REDIS_PASSWORD: *REDIS_PASSWORD
      REDIS_DB: *REDIS_DB
    ports:
    - '18888:18888'

  grpc-server:
    depends_on:
    - nats
    - redis
    build:
      context: ./whiteboard-server/
      target: grpc-server
    image: grpc-server
    hostname: grpc-server
    container_name: grpc-server
    restart: unless-stopped
    environment:
      PORT: '10000'
      NATS_USER: *NATS_USER
      NATS_PASS: *NATS_PASS
      REDIS_HOST: *REDIS_HOST
      REDIS_PORT: *REDIS_PORT
      REDIS_PASSWORD: *REDIS_PASSWORD
      REDIS_DB: *REDIS_DB
      GRPC_GO_LOG_SEVERITY_LEVEL: info
      GRPC_GO_LOG_VERBOSITY_LEVEL: 99
    ports:
    - '10000:10000'
