version: '3.8'
services:

  nats:
    image: docker.io/library/nats:2-alpine@sha256:eeb7529aaf3ccea4398dad18e815a82b8b116696b7f031b4126b00061ddb1093
    environment:
      # Only here so refs can be bound
      _1: &NATS_USER 'reMarkable-HyperCards'
      _2: &NATS_PASS 'iQ9KE4XNiq9XmCmGbbyjsQ7KP9DMHXL6yLGeFHfj'
    command:
    - --user
    - *NATS_USER
    - --pass
    - *NATS_PASS
    - -m
    - '8222'
    - -DVV
    # ports:
    # - '127.0.0.1:4222:4222'
    # - '127.0.0.1:6222:6222'
    # - '127.0.0.1:8222:8222'

  redis:
    image: docker.io/library/redis:5-alpine@sha256:cb5840073dc475b45bf856eb666f5e4d19e3b1ae882e0f3a1396d399cfa23702
    environment:
      # Only here so refs can be bound
      _1: &REDIS_HOST 'redis'
      _2: &REDIS_PORT '6379'
    volumes:
    - ./redis/redis.conf:/etc/redis/redis.conf:ro
    command: redis-server /etc/redis/redis.conf
    # ports:
    # - '127.0.0.1:6379:6379'

  http-server:
    depends_on:
    - redis
    build:
      context: ./whiteboard-server/
      target: http-server
    image: http-server
    hostname: http-server
    container_name: http-server
    restart: unless-stopped
    environment:
      PORT: '18888'
      PATH_PREFIX: /s
      REDIS_HOST: *REDIS_HOST
      REDIS_PORT: *REDIS_PORT
    ports:
    - '18888:18888'

  grpc-server:
    depends_on:
    - nats
    - redis
    build:
      context: ./whiteboard-server/
      target: grpc-server
    image: grpc-server
    hostname: grpc-server
    container_name: grpc-server
    restart: unless-stopped
    environment:
      PORT: '10000'
      NATS_USER: *NATS_USER
      NATS_PASS: *NATS_PASS
      REDIS_HOST: *REDIS_HOST
      REDIS_PORT: *REDIS_PORT
      GRPC_GO_LOG_SEVERITY_LEVEL: info
      GRPC_GO_LOG_VERBOSITY_LEVEL: 99
    ports:
    - '10000:10000'
