[package]
name = "marauder"
version = "0.1.0"
authors = ["Pierre Fenoll <pierrefenoll@gmail.com>"]
edition = "2018"

[profile.release]
debug = true
lto = "thin"

[dependencies]
atomic = { version = "0.4.5", features = ["nightly"] }
chrono = "0.4.11"
env_logger = "0.7.1"
itertools = "0.9.0"
lazy_static = "1.4.0"
libremarkable = { git = "https://github.com/canselcik/libremarkable" }
log = "0.4.8"
rand = "0.7.3"
