[package]
name = "marauder"
version = "0.1.0"
authors = ["Pierre Fenoll <pierrefenoll@gmail.com>"]
edition = "2018"

[profile.release]
debug = true
lto = "thin"

[dependencies]
atomic = { version = "^0", features = ["nightly"] }
chrono = "^0"
env_logger = "^0"
itertools = "^0"
lazy_static = "^1"
libremarkable = { git = "https://github.com/canselcik/libremarkable" }
log = "^0"
rand = "^0"
