[package]
name = "marauder"
version = "0.1.0"
authors = ["Pierre Fenoll <pierrefenoll@gmail.com>"]
edition = "2018"

[profile.release]
debug = true
lto = true

[dependencies]
atomic = { version = "0.4.5", features = ["nightly"] }
chrono = "0.4.11"
env_logger = "0.7.1"
lazy_static = "1.4.0"
libremarkable = { git = "https://github.com/fenollp/libremarkable", branch = "nits" } # TODO: https://github.com/canselcik/libremarkable/pull/28
log = "0.4.8"
