[package]
name = "marauder"
version = "0.2.0"
authors = ["Pierre Fenoll <pierrefenoll@gmail.com>"]
edition = "2018"

[profile.release]
lto = "fat" # "fat" xor "thin". "thin" is faster but crashes on some binaries

[dependencies]
atomic = { version = "^0", features = ["nightly"] }
chrono = "^0"
env_logger = "^0"
itertools = "^0"
lazy_static = "^1"
libremarkable = { git = "https://github.com/canselcik/libremarkable" }
log = "^0"
nom = "5"
rand = "^0"

tonic = "0.3"
prost = "0.6"
tokio = { version = "0.2", features = ["rt-threaded", "rt-core", "time", "stream", "fs", "macros", "uds"] }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
async-stream = "0.2"
tower = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"

docopt = "1"
nats = "0.7"

[build-dependencies]
tonic-build = "0.3"
