[package]
name = "marauder"
version = "0.3.5"
authors = ["Pierre Fenoll <pierrefenoll@gmail.com>"]
edition = "2021"

[dependencies]
async-stream = "0.3"
atomic = "0.5"
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
crc-any = { version = "2", default-features = false, features = ["heapless"] }
env_logger = "0.10"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
itertools = "0.11"
libremarkable = "0.6" # libremarkable = { git = "https://github.com/canselcik/libremarkable", branch = "master" }
log = "0.4"
nom = "7"
once_cell = "1"
prost = "0.9"
qrcode-generator = "4"
quick-xml = { version = "0.22", features = ["serialize"] }
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "time", "fs", "macros", "net"] }
tokio-stream = { version =  "0.1", features = ["net"] }
tonic = { version = "0.6", features = ["compression"] }
tower = { version = "0.4" }
uuid = { version = "1", features = ["v4"] }

[build-dependencies]
tonic-build = { version = "0.6", features = ["compression"] }
