[package]
name = "marauder"
version = "0.3.3"
authors = ["Pierre Fenoll <pierrefenoll@gmail.com>"]
edition = "2018"

[profile.release]
lto = "thin" # "fat" xor "thin". "thin" is faster but crashes on some binaries

[dependencies]
atomic = "^0"
chrono = "^0"
env_logger = "^0"
itertools = "^0"
once_cell = "1.7.2"
libremarkable = "0.5.0"
log = "^0"
nom = "5"
rand = "^0"
image = "0.21.3" # matches libremarkable's

tonic = "0.5"
prost = "0.8"
tokio = { version = "1", features = ["full"] }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
async-stream = "0.2"
tower = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"

structopt = "0.3"
uuid = { version = "0.8", features = ["v4"] }

quick-xml = { version = "0.22", features = ["serialize"] }

crc-any = { version = "2.3.12", default-features = false, features = ["heapless"] }

qrcode-generator = "4.1.1"

[build-dependencies]
tonic-build = "0.5"
