# https://github.com/toltec-dev/toolchain/blob/cb0b263d908c1fc80ec8d0fc03c2b8f020d58c95/rust/config

[build]
target = "armv7-unknown-linux-gnueabihf"

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
rustflags = [
    "-C", "link-arg=-march=armv7-a",
    "-C", "link-arg=-marm",
    "-C", "link-arg=-mfpu=neon",
    "-C", "link-arg=-mfloat-abi=hard",
    "-C", "link-arg=-mcpu=cortex-a9",
]
