#!/bin/sh -eux

echo $(id -u) >&2
echo $(id -g) >&2

echo \$@: "$@" >&2

echo \$PWD: "$PWD" >&2

echo \$USER: "$USER" >&2
echo \$HOME: "$HOME" >&2

ls -lha / >&2 || true
ls -lha /usr >&2 || true
ls -lha /usr/bin >&2 || true
ls -lha /usr/bin/docker >&2 || true

su pete
whoami >&2 || truee
newgrp docker >&2 || true ######

ls -lha ./protoc >&2 || true
ls -lha /home/pete/wefwefwef/reMarkable-tools.git/pb/protoc >&2 || true

whereis docker >&2 || true
which docker >&2 || true

stat /usr/bin/docker >&2 || true

exec /usr/bin/docker run \
       --rm \
       -v "$PWD":"$PWD" \
       -v /tmp:/tmp \
       -w "$PWD" \
       znly/protoc:0.4.0 \
       --proto_path="$PWD"/ \
       "$@" >&2
